# wrangler.toml
name = "riddle-backend"
main = "worker.js"
compatibility_date = "2024-03-20"

# 允許跨域請求 (設定為 * 代表允許你的前端呼叫)
[vars]
ALLOWED_ORIGIN = "*"

# 綁定你申請好的 D1 資料庫
[[d1_databases]]
binding = "DB"
database_name = "riddle-db"
database_id = "2c8b5570-44b1-48a9-a067-eb1a0e010f35"

