# wrangler.toml
name = "riddle-backend"
main = "worker.js"
compatibility_date = "2024-03-20"

# 允許跨域請求 (CORS)
[vars]
ALLOWED_ORIGIN = "*" # 未來可以改成你的 Pages 網址，例如 "https://riddle-notebook.pages.dev"

# 綁定你的 D1 資料庫
[[d1_databases]]
binding = "DB"
database_name = "riddle-db"
database_id = "2c8b5570-44b1-48a9-a067-eb1a0e010f35"

